services:
  nginx:
    image: nginx:latest
    container_name: "rest_project_nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro # Прокидываем конфиг
      - ./static:/var/www/html/static
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "rest_project_web"
    env_file:
      - .env
    # Порт 8000 убираем из ports, он будет доступен внутри сети для Nginx
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:18.0-alpine
    container_name: "rest_project_db"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    container_name: "rest_project_redis"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5

  celery_worker:
    build: .
    container_name: "rest_project_celery_worker"
    env_file:
      - .env
    command: celery -A config worker -l info # Путь изменен
    depends_on:
      redis:
        condition: service_healthy

  celery_beat:
    build: .
    container_name: "rest_project_celery_beat"
    env_file:
      - .env
    command: celery -A config beat -l info # Путь изменен
    depends_on:
      redis:
        condition: service_healthy

volumes:
  postgres_data:
